### ISSUE TITLE
Unsure how to Adapt to Wordpress install

### ISSUE THREAD

**Issue by AmGarera** [bstavroulakis/vue-wordpress-pwa#2]
Hi, I'm attempting to adapt this to one of my wordpress installs and it's not clear how to exactly do that. Any help would be greatly appreciated.

**Comment by bstavroulakis** [comment]
Hello Anthony,
This project isn't your typical plug and play PHP Wordpress theme. But works as a client for your Wordpress Installation consuming the Wordpress REST v2 API. So this client would be running on the cloud somewhere at http://your-blog.com and your Wordpress installation could be at http://api.your-blog-service.com.

Before you build the project you can play around with the app.config.js file to change the client and rest path and the server.js file (to change the CDN path).

**Comment by AmGarera** [comment]
Thanks, that was my assumption! My plan was to host this on Netlify and keep my WordPress back end on Digital Ocean. If I'm developing locally what should the client path be?

**Comment by bstavroulakis** [comment]
The client is the path of the site that is actually running the client app. So locally it could be localhost or 127.0.0.1 or any local domain you are using.
