### ISSUE TITLE
Error in render function: "TypeError: Cannot read property 'Link' of undefined"

### ISSUE THREAD

**Issue by ssuess** [bstavroulakis/vue-wordpress-pwa#4]
Hi I am getting this error in the console. None of my individual posts were loading (although the main category group was) until I removed this line from vwpSingle.vue:

`<a :href="single.rest_api_enabler.Link" target="_blank">{{single.rest_api_enabler.Link}}</a>`

Any pointers on where I might look to fix this?

**Comment by bstavroulakis** [comment]
Thanks, I included an extra check when the rest_api_enabler wordpress plugin is missing => 4c6b53c1a0d0ce27f7980a383a6cf43269c6ac07
