### ISSUE TITLE
offline

### ISSUE THREAD

**Issue by yoanmarchal** [bstavroulakis/vue-wordpress-pwa#5]
offline mode don't work

**Comment by djmtype** [comment]
+1 When offline, the page will render a cached version without the CSS and JS. Otherwise, nothing will render.

**Comment by bstavroulakis** [comment]
Will look into this. Although it passes the Lighthouse tests we may have to pre-cache some more pages for this to work. I will investigate, thanks!

**Comment by bstavroulakis** [comment]
The app-shell will load now, even when you're offline and haven't visited the page before d6a60647ef66d2a389582f176ab7f2bbdcb6fcc6.

If you could please check this one again @yoanmarchal @djmtype. Thank you

**Comment by bstavroulakis** [comment]
Fixed. Now if you're offline it will always load the app-shell 88bbfdc7a5b8804fc9dc86a3cf86006865380537
