### ISSUE TITLE
Error when deploying to Azure

### ISSUE THREAD

**Issue by ggPixel** [bstavroulakis/vue-wordpress-pwa#94]
Hi,

I tried deploying this is Azure but got some errors.

1. Basically I setup an App Service in Azure
2. I used the Web App option using Linux OS.
3. Runtime Stack I used is Node.js v9.4

Here's the errors I got when deploying:

````Command: build/deploy.cmd
/home/site/repository/build/deploy.cmd: line 1: call: command not found
/home/site/repository/build/deploy.cmd: line 2: IF: command not found
/home/site/repository/build/deploy.cmd: line 4: call: command not found
/home/site/repository/build/deploy.cmd: line 5: IF: command not found
/home/site/repository/build/deploy.cmd: line 7: syntax error near unexpected token `%%D'
/home/site/repository/build/deploy.cmd: line 7: `for /d %%D in (%DEPLOYMENT_TARGET%\*) do ('
/home/site/repository/build/deploy.cmd: line 1: call: command not found\n/home/site/repository/build/deploy.cmd: line 2: IF: command not found\n/home/site/repository/build/deploy.cmd: line 4: call: command not found\n/home/site/repository/build/deploy.cmd: line 5: IF: command not found\n/home/site/repository/build/deploy.cmd: line 7: syntax error near unexpected token `%%D'\n/home/site/repository/build/deploy.cmd: line 7: `for /d %%D in (%DEPLOYMENT_TARGET%\*) do ('\n/opt/Kudu/bin/Scripts/starter.sh build/deploy.cmd
````

Sorry I'm new to this so not sure if I did something wrong.

**Comment by bstavroulakis** [comment]
Ah yes, the deploy.cmd is targeted for a Windows machine.

For a Linux machine you can create a deploy.sh files and translate the deploy.cmd command to bash commands.

You can check out an example over here
https://github.com/dotnetweekly/dnw-pwa/blob/master/.deployment
https://github.com/dotnetweekly/dnw-pwa/blob/master/build/deploy.sh

**Comment by ggPixel** [comment]
Blond moment, thanx @bstavroulakis
